import { ArrowLeft, ChevronDown, Edit3, MoreHorizontal, Plus, Trophy, Trash2 } from 'lucide-react'
import { useState } from 'react'
import { useLiveQuery } from 'dexie-react-hooks'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { ConfirmDialog } from '../../components/Modal'
import { useToast } from '../../components/Toast'
import { calculateProgress, statusLabels, statusStyles } from '../../domain/rules'
import type { MilestoneInput, NodeInput, PraxisNode, ProjectInput, ReviewInput, ReviewTrigger } from '../../domain/types'
import { nodeTypes, projectStatuses } from '../../domain/types'
import { repository } from '../../repositories/repository'
import { MilestoneForm } from '../milestones/MilestoneForm'
import { milestoneResultMeta, NodeCard, nodeTypeMeta } from '../nodes/NodeCard'
import { NodeForm } from '../nodes/NodeForm'
import { ReviewForm } from '../reviews/ReviewForm'
import { ProjectForm } from './ProjectForm'

export function ProjectDetailPage() {
  const { projectId = '' } = useParams(); const navigate = useNavigate(); const bundle = useLiveQuery(() => repository.getBundle(projectId), [projectId]); const { notify } = useToast()
  const [projectForm, setProjectForm] = useState(false); const [nodeForm, setNodeForm] = useState(false); const [editingNode, setEditingNode] = useState<PraxisNode | null>(null); const [defaultType, setDefaultType] = useState<NodeInput['type']>('question'); const [milestoneNode, setMilestoneNode] = useState<PraxisNode | null>(null); const [reviewOpen, setReviewOpen] = useState(false); const [reviewTrigger, setReviewTrigger] = useState<ReviewTrigger>('manual'); const [confirm, setConfirm] = useState<{ kind: 'project' | 'node' | 'complete'; id?: string } | null>(null)
  if (bundle === undefined) return <div className="page-wrap"><div className="h-40 animate-pulse rounded-[var(--radius-card)] bg-surface/60" /></div>
  if (bundle === null) return <div className="page-wrap text-center"><h1 className="page-title">项目不存在</h1><Link className="button-primary mt-6" to="/projects">返回项目列表</Link></div>
  const { project, nodes, milestones, reviews } = bundle; const progress = calculateProgress(nodes)
  const saveProject = async (input: ProjectInput) => { await repository.updateProject(project.id, input); setProjectForm(false); notify('项目信息已修正') }
  const saveNode = async (input: NodeInput) => { await repository.saveNode(project.id, input, editingNode?.id); setNodeForm(false); setEditingNode(null); notify('节点已保存') }
  const openNode = (type: NodeInput['type'], node?: PraxisNode) => { setDefaultType(type); setEditingNode(node ?? null); setNodeForm(true) }
  const saveMilestone = async (input: MilestoneInput) => { if (!milestoneNode) return; const previous = milestones.find((item) => item.nodeId === milestoneNode.id); await repository.saveMilestone(project.id, milestoneNode.id, input); setMilestoneNode(null); notify(input.result ? '验证结果已保存' : '里程碑已建立'); if (input.result && input.result !== previous?.result) { setReviewTrigger('milestone'); setReviewOpen(true) } }
  const saveReview = async (input: ReviewInput) => { await repository.saveReview(project.id, input); setReviewOpen(false); notify('审视记录已保存') }
  const changeStatus = async (status: typeof project.status) => { try { await repository.setProjectStatus(project.id, status); notify(`项目已切换为${statusLabels[status]}`); if (status === 'completed') { setReviewTrigger('project_end'); setReviewOpen(true) } } catch (error) { if (error instanceof Error && error.message === 'NO_PASSED_MILESTONE') setConfirm({ kind: 'complete' }); else notify(error instanceof Error ? error.message : '状态切换失败', 'error') } }
  const executeConfirm = async () => { if (!confirm) return; if (confirm.kind === 'project') { await repository.deleteProject(project.id); navigate('/projects'); notify('项目及关联记录已删除', 'info') } else if (confirm.kind === 'node' && confirm.id) { await repository.deleteNode(confirm.id); notify('节点已删除', 'info') } else { await repository.setProjectStatus(project.id, 'completed', true); setReviewTrigger('project_end'); setReviewOpen(true); notify('项目已强制完成') } setConfirm(null) }
  return <div className="page-wrap"><Link to="/projects" className="link-subtle inline-flex items-center gap-2"><ArrowLeft size={16} />返回项目总览</Link>
    <header className="project-detail-hero surface-card mt-7 p-6 sm:p-8"><div className="relative z-[1] flex flex-col gap-7 xl:flex-row xl:items-start xl:justify-between"><div className="max-w-4xl"><div className="flex flex-wrap items-center gap-3"><span className={`status-badge ${statusStyles[project.status]}`}>{statusLabels[project.status]}</span><span className="text-xs text-text-secondary">更新于 {new Date(project.updatedAt).toLocaleString('zh-CN')}</span></div><h1 className="mt-5 font-serif text-4xl font-semibold leading-tight text-text-primary sm:text-5xl">{project.title}</h1><div className="mt-5 border-l-2 border-accent-primary pl-4"><p className="text-xs font-semibold uppercase tracking-widest text-accent-primary">现实触发</p><p className="mt-2 leading-7 text-text-secondary">{project.trigger}</p></div></div><div className="flex shrink-0 gap-2"><button className="button-secondary" onClick={() => setProjectForm(true)}><Edit3 size={16} />编辑</button><button className="icon-button !h-11 !w-11" onClick={() => setConfirm({ kind: 'project' })} title="删除项目"><Trash2 size={17} /></button></div></div><div className="relative z-[1] mt-8 grid gap-6 border-t border-line/15 pt-6 md:grid-cols-[1fr_auto]"><div><div className="mb-2 flex justify-between text-xs text-text-secondary"><span>{progress.completed} / {progress.total} 有效节点完成</span><span>{progress.percent}%</span></div><div className="progress-track h-2"><div className="progress-fill" style={{ width: `${progress.percent}%` }} /></div></div><label className="flex items-center gap-3 text-xs text-text-secondary"><span>项目状态</span><select className="rounded-xl border border-line/15 bg-panel px-3 py-2 text-sm text-text-primary" value={project.status} onChange={(event) => changeStatus(event.target.value as typeof project.status)}>{projectStatuses.map((status) => <option key={status} value={status}>{statusLabels[status]}</option>)}</select></label></div></header>
    <div className="project-workspace mt-8 grid gap-8 2xl:grid-cols-[minmax(0,1fr)_360px]"><main><div className="flex items-end justify-between"><div><p className="eyebrow">实践路线</p><h2 className="mt-1 font-serif text-3xl text-text-primary">节点链</h2></div><div className="group relative"><button className="button-primary"><Plus size={17} />添加节点<ChevronDown size={15} /></button><div className="invisible absolute right-0 top-full z-20 mt-2 w-48 rounded-2xl border border-line/15 bg-surface p-2 opacity-0 shadow-card transition group-hover:visible group-hover:opacity-100 group-focus-within:visible group-focus-within:opacity-100">{nodeTypes.map((type) => { const Meta = nodeTypeMeta[type]; return <button key={type} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-text-primary hover:bg-surface2" onClick={() => openNode(type)}><Meta.icon size={17} />{Meta.label}节点</button> })}</div></div></div>
      {nodes.length ? <div className="detail-timeline relative mt-6 space-y-4">{nodes.map((node, index) => <NodeCard key={node.id} node={node} milestone={milestones.find((item) => item.nodeId === node.id)} first={index === 0} last={index === nodes.length - 1} onEdit={() => openNode(node.type, node)} onDelete={() => setConfirm({ kind: 'node', id: node.id })} onMove={(direction) => repository.moveNode(node.id, direction)} onMilestone={() => setMilestoneNode(node)} onNewSolution={() => openNode('solution')} />)}</div> : <div className="surface-ghost mt-6 p-14 text-center"><MoreHorizontal className="mx-auto text-accent-primary" /><h3 className="mt-4 font-serif text-2xl text-text-primary">从第一个问题开始</h3><p className="mt-2 text-sm text-text-secondary">将触发源提炼成一个可以探索和回答的问题。</p><button className="button-primary mt-5" onClick={() => openNode('question')}><Plus size={17} />添加问题节点</button></div>}</main>
      <aside className="space-y-5"><section className="milestone-panel validation-terminal checkpoint-panel"><div className="flex items-center justify-between"><p className="milestone-kicker text-xs uppercase tracking-widest"><span className="theme-label-default">里程碑</span><span className="tech-only">Validation Terminal</span><span className="game-only">Quest Checkpoints</span></p><span className="checkpoint-emblem"><Trophy size={19} className="text-accent-primary" /></span></div><p className="milestone-score mt-4 font-serif text-3xl text-[rgb(var(--milestone-fg))]">{milestones.filter((item) => item.result === 'passed').length}<span className="text-lg milestone-subtle"> / {milestones.length}</span></p><p className="mt-1 text-xs milestone-subtle">验证通过</p>{milestones.length > 0 && <div className="mt-5 space-y-2">{milestones.map((item) => <button key={item.id} className="milestone-chip flex w-full items-center justify-between" onClick={() => setMilestoneNode(nodes.find((node) => node.id === item.nodeId) ?? null)}><span className="truncate">{item.title}</span><span>{item.result ? milestoneResultMeta[item.result].label : '待验证'}</span></button>)}</div>}</section><section className="diagnostic-panel surface-card p-6"><div className="relative z-[1] flex items-center justify-between"><div><p className="eyebrow"><span className="theme-label-default">反馈修正</span><span className="tech-only">Diagnostic Reports</span><span className="game-only">Journey Log</span></p><h3 className="mt-1 font-serif text-xl text-text-primary">审视记录</h3></div><button className="icon-button" onClick={() => { setReviewTrigger('manual'); setReviewOpen(true) }} title="新增审视"><Plus size={16} /></button></div>{reviews.length ? <div className="relative z-[1] mt-5 space-y-3">{reviews.slice(0, 3).map((review) => <div key={review.id} className="review-card"><p className="text-xs font-medium text-text-primary">{review.health}</p><p className="mt-1 text-[10px] text-text-secondary">{new Date(review.createdAt).toLocaleDateString('zh-CN')}</p></div>)}</div> : <p className="relative z-[1] mt-4 text-sm leading-6 text-text-secondary">关键验证后停下来，检查路线是否仍符合现实。</p>}<button className="relative z-[1] mt-5 text-xs font-medium text-accent-primary" onClick={() => { setReviewTrigger('manual'); setReviewOpen(true) }}>开始一次主动审视 →</button></section></aside></div>
    <ProjectForm open={projectForm} project={project} onClose={() => setProjectForm(false)} onSubmit={saveProject} /><NodeForm open={nodeForm} node={editingNode} defaultType={defaultType} onClose={() => { setNodeForm(false); setEditingNode(null) }} onSubmit={saveNode} /><MilestoneForm open={Boolean(milestoneNode)} milestone={milestones.find((item) => item.nodeId === milestoneNode?.id)} onClose={() => setMilestoneNode(null)} onSubmit={saveMilestone} onDelete={async () => { if (!milestoneNode) return; await repository.deleteMilestone(milestoneNode.id); setMilestoneNode(null); notify('已取消里程碑', 'info') }} /><ReviewForm open={reviewOpen} trigger={reviewTrigger} onClose={() => setReviewOpen(false)} onSubmit={saveReview} /><ConfirmDialog open={Boolean(confirm)} title={confirm?.kind === 'project' ? '删除整个项目？' : confirm?.kind === 'node' ? '删除这个节点？' : '缺少通过的里程碑'} message={confirm?.kind === 'project' ? '项目、节点、里程碑和审视记录将一起永久删除。' : confirm?.kind === 'node' ? '如果节点关联里程碑，验证记录也会一并删除。' : '该项目尚无验证通过的里程碑。仍然可以强制完成，但建议先用实践结果验证路线。'} danger={confirm?.kind !== 'complete'} confirmLabel={confirm?.kind === 'complete' ? '仍然完成' : '确认删除'} onClose={() => setConfirm(null)} onConfirm={executeConfirm} />
  </div>
}
