import { expect, test } from '@playwright/test'

test('核心实践闭环与当前路线', async ({ page }) => {
  await page.goto('/projects')
  await page.getByRole('button', { name: '开启新项目', exact: true }).click()
  await page.getByLabel('项目名称').fill('当前路线测试项目')
  await page.getByLabel('现实触发').fill('验证路线推进和支线行为')
  await page.getByRole('button', { name: '创建项目' }).click()
  await page.getByRole('link', { name: /当前路线测试项目/ }).click()
  await page.getByRole('button', { name: '添加节点' }).hover()
  await page.getByRole('button', { name: '问题节点', exact: true }).click()
  await page.getByLabel('节点内容').fill('起点问题')
  await page.getByRole('button', { name: '保存节点' }).click()
  await expect(page.getByText('当前目标', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '继续推进' }).last().click()
  await page.getByLabel('节点内容').fill('推进方案')
  await page.getByRole('button', { name: '保存节点' }).click()
  await expect(page.getByText('0 / 2 当前路线节点完成')).toBeVisible()
  await page.getByRole('button', { name: '创建支线' }).click()
  await page.getByLabel('节点内容').fill('备用支线')
  await page.getByRole('button', { name: '保存节点' }).click()
  await expect(page.getByText('0 / 2 当前路线节点完成')).toBeVisible()
  await page.getByRole('button', { name: '节点列表' }).click()
  await expect(page.getByText('当前目标', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '设为里程碑' }).first().click()
  await page.getByLabel('里程碑名称').fill('核心闭环可用')
  await page.getByLabel('验证方式').fill('运行真实流程')
  await page.getByLabel('通过标准').fill('路线和验证均可用')
  await page.getByLabel('验证结果').selectOption('passed')
  await page.getByLabel('结果感受').fill('符合预期')
  await page.getByRole('button', { name: '创建里程碑' }).click()
  await page.getByLabel('1. 当前项目健康度如何？').fill('项目路线清晰')
  await page.getByLabel('2. 最近的执行模式是否有问题？').fill('执行节奏正常')
  await page.getByLabel('3. 系统本身是否需要调整？').fill('无需调整')
  await page.getByRole('button', { name: '保存审视' }).click()
  await expect(page.getByText('1 / 1')).toBeVisible()
})
