import { expect, test } from '@playwright/test'

test('核心实践闭环', async ({ page }) => {
  await page.goto('/projects')
  await page.getByRole('button', { name: /开启新项目|创建第一个项目/ }).click()
  await page.getByLabel('项目名称').fill('开发个人任务管理系统')
  await page.getByLabel('现实触发').fill('需要用真实项目验证认知—实践闭环')
  await page.getByRole('button', { name: '创建项目' }).click()
  await page.getByRole('link', { name: /开发个人任务管理系统/ }).click()
  await page.getByRole('button', { name: '添加节点' }).hover()
  await page.getByRole('button', { name: '问题节点' }).click()
  await page.getByLabel('节点内容').fill('怎样构建可持续修正的个人执行系统？')
  await page.getByRole('button', { name: '保存节点' }).click()
  await page.getByRole('button', { name: '设为里程碑' }).click()
  await page.getByLabel('里程碑名称').fill('核心闭环可用')
  await page.getByLabel('验证方式').fill('连续使用一个真实项目')
  await page.getByLabel('通过标准').fill('能够记录节点并完成验证')
  await page.getByLabel('验证结果').selectOption('passed')
  await page.getByLabel('结果感受').fill('流程符合预期')
  await page.getByRole('button', { name: '创建里程碑' }).click()
  await page.getByLabel('1. 当前项目健康度如何？').fill('项目路线清晰')
  await page.getByLabel('2. 最近的执行模式是否有问题？').fill('执行节奏正常')
  await page.getByLabel('3. 系统本身是否需要调整？').fill('后续增加日志搜索')
  await page.getByRole('button', { name: '保存审视' }).click()
  await expect(page.getByText('1 / 1')).toBeVisible()
})
