import { expect, test } from '@playwright/test'

test('节点 Markdown 在预览、详情与日志中安全渲染', async ({ page }) => {
  const imageRequests: string[] = []; page.on('request', (request) => { if (request.url().startsWith('https://images.example/')) imageRequests.push(request.url()) })
  await page.goto('/projects')
  await page.getByRole('button', { name: '开启新项目', exact: true }).click()
  await page.getByLabel('项目名称').fill('Markdown 科研记录')
  await page.getByLabel('现实触发').fill('验证公式与代码显示')
  await page.getByRole('button', { name: '创建项目' }).click()
  await page.getByRole('link', { name: /Markdown 科研记录/ }).click()
  await page.getByRole('button', { name: '添加节点' }).hover()
  await page.getByRole('button', { name: '问题节点', exact: true }).click()

  const contentSource = ['# 研究结论', '', '- [x] 已验证', '', '公式 $E = mc^2$', '', '```typescript', 'const answer: number = 42', '```', '', '![实验曲线](https://images.example/plot.png)'].join('\n')
  const logSource = ['## 实验日志', '', '> 结果稳定', '', '$$', '\\lim_{n\\to\\infty} x_n = x^*', '$$', '', '```python', 'print("done")', '```'].join('\n')
  const contentField = page.locator('.markdown-editor-field').filter({ has: page.getByText('节点内容', { exact: true }) })
  const logField = page.locator('.markdown-editor-field').filter({ has: page.getByText('附加日志', { exact: false }) })
  await page.getByLabel('节点内容').fill(contentSource)
  await page.getByLabel(/附加日志/).fill(logSource)
  await contentField.getByRole('tab', { name: '预览' }).click()
  await expect(contentField.getByRole('heading', { name: '研究结论' })).toBeVisible()
  await expect(contentField.locator('.katex')).toBeVisible()
  await expect(contentField.locator('code.hljs.language-typescript')).toContainText('const answer')
  await expect(contentField.getByRole('link', { name: '图片链接：实验曲线' })).toBeVisible()
  await expect(contentField.locator('img')).toHaveCount(0)
  await logField.getByRole('tab', { name: '预览' }).click()
  await expect(logField.getByRole('heading', { name: '实验日志' })).toBeVisible()
  await expect(logField.locator('.katex-display')).toBeVisible()
  await expect(logField.locator('code.hljs.language-python')).toContainText('print')
  await page.getByRole('button', { name: '保存节点' }).click()

  const graphNode = page.locator('.graph-node', { hasText: '研究结论' })
  await expect(graphNode).toBeVisible()
  await expect(graphNode.locator('.graph-node-content')).not.toContainText('#')
  await expect(graphNode).toHaveCSS('height', '220px')
  const intel = page.locator('.graph-intel-panel')
  await expect(intel.getByRole('heading', { name: '研究结论' })).toBeVisible()
  await expect(intel.locator('.katex')).toBeVisible()
  await expect(intel.locator('code.hljs.language-typescript')).toContainText('const answer')

  await page.getByRole('button', { name: '节点列表' }).click()
  const card = page.locator('.node-card', { hasText: '研究结论' })
  await expect(card.getByRole('heading', { name: '研究结论' })).toBeVisible()
  await card.getByRole('button', { name: '成果与感受' }).click()
  await expect(card.getByRole('heading', { name: '实验日志' })).toBeVisible()
  await expect(card.locator('.katex-display')).toBeVisible()
  await expect(card.locator('code.hljs.language-python')).toContainText('print')
  await expect(card.locator('img')).toHaveCount(0)
  expect(imageRequests).toEqual([])

  await page.getByRole('button', { name: '添加节点' }).hover()
  await page.getByRole('button', { name: '问题节点', exact: true }).click()
  await page.getByLabel('节点内容').fill('全屏中的沉浸书写内容')
  await contentField.getByRole('button', { name: '全屏', exact: true }).click()
  await expect(page.locator('.editor-fullscreen')).toBeVisible()
  await expect(page.getByLabel('节点内容')).toHaveValue('全屏中的沉浸书写内容')
  await page.keyboard.press('Control+Shift+v')
  await expect(contentField.locator('.markdown-preview')).toContainText('全屏中的沉浸书写内容')
  await expect(page.getByLabel('节点内容')).toHaveCount(0)
  await page.keyboard.press('Control+Shift+v')
  await expect(page.getByLabel('节点内容')).toHaveValue('全屏中的沉浸书写内容')
  await page.keyboard.press('Escape')
  await expect(page.locator('.editor-fullscreen')).toHaveCount(0)
  await expect(page.getByLabel('节点内容')).toHaveValue('全屏中的沉浸书写内容')
  await page.getByRole('button', { name: '取消', exact: true }).click()
})
