import dagre from '@dagrejs/dagre'
import { Background, Controls, MarkerType, ReactFlow, useEdgesState, useNodesState, type Connection, type Edge, type ReactFlowInstance } from '@xyflow/react'
import { Crosshair, Edit3, Flag, GitBranch, LocateFixed, Map as MapIcon, Plus, Target, Trash2, Unlink } from 'lucide-react'
import { useCallback, useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react'
import type { CurrentRoute } from '../../domain/graph'
import { findCollapsedBranchForNode, getCollapsibleBranches, resolveCollapsedGraph } from '../../domain/graph-visibility'
import { useTheme } from '../../theme/ThemeProvider'
import type { Milestone, NodeConnection, PraxisNode } from '../../domain/types'
import { getGraphEdgeState, getGraphVisualState } from './graphVisualState'
import { GraphMiniMap } from './GraphMiniMap'
import { RouteMapEdge } from './RouteMapEdge'
import { BranchSummaryNode, graphNodeHeight, graphNodeWidth, TaskGraphNode, techGraphNodeHeight, type BranchSummaryFlowNode, type TaskFlowNode } from './TaskGraphNode'
import { useReducedMotion, useRouteTransition } from './useRouteTransition'

type GraphFlowNode = TaskFlowNode | BranchSummaryFlowNode
function layoutGraph(nodes: GraphFlowNode[], edges: Edge[], nodeHeight = graphNodeHeight) { const graph = new dagre.graphlib.Graph().setDefaultEdgeLabel(() => ({})); graph.setGraph({ rankdir: 'LR', ranksep: 118, nodesep: 70, marginx: 70, marginy: 65 }); nodes.forEach((node) => graph.setNode(node.id, { width: node.type === 'branchSummary' ? 190 : graphNodeWidth, height: node.type === 'branchSummary' ? 96 : nodeHeight })); edges.forEach((edge) => graph.setEdge(edge.source, edge.target)); dagre.layout(graph); return nodes.map((node) => { const point = graph.node(node.id); const width = node.type === 'branchSummary' ? 190 : graphNodeWidth; const height = node.type === 'branchSummary' ? 96 : nodeHeight; return { ...node, position: { x: point.x - width / 2, y: point.y - height / 2 } } }) }

interface Props { projectId: string; activeNodeId: string | null; route: CurrentRoute; nodes: PraxisNode[]; connections: NodeConnection[]; milestones: Milestone[]; selectedNodeId: string | null; onSelectNode: (node: PraxisNode) => void; onAdvance: (node: PraxisNode) => void; onBranch: (node: PraxisNode) => void; onSetActive: (node: PraxisNode) => void; onClearActive: () => void; onEdit: (node: PraxisNode) => void; onDelete: (node: PraxisNode) => void; onMilestone: (node: PraxisNode) => void; onConnect: (sourceId: string, targetId: string) => Promise<void>; onDisconnect: (connectionId: string) => Promise<void> }

export function TaskGraph({ projectId, activeNodeId, route, nodes: domainNodes, connections, milestones, selectedNodeId, onSelectNode, onAdvance, onBranch, onSetActive, onClearActive, onEdit, onDelete, onMilestone, onConnect, onDisconnect }: Props) {
  const { theme } = useTheme()
  const routeNodes = useMemo(() => new Set(route.nodeIds), [route.nodeIds]); const routeEdges = useMemo(() => new Set(route.connectionIds), [route.connectionIds]); const nodeById = useMemo(() => new Map(domainNodes.map((node) => [node.id, node])), [domainNodes]); const milestoneByNode = useMemo(() => new Map(milestones.map((item) => [item.nodeId, item])), [milestones])
  const visualById = useMemo(() => new Map(domainNodes.map((node) => [node.id, getGraphVisualState(node, route, activeNodeId)])), [activeNodeId, domainNodes, route]); const branches = useMemo(() => getCollapsibleBranches(domainNodes, connections, route), [connections, domainNodes, route]); const [collapsedIds, setCollapsedIds] = useState<Set<string>>(new Set()); const [instance, setInstance] = useState<ReactFlowInstance<GraphFlowNode, Edge> | null>(null); const reduceMotion = useReducedMotion(); const transitioning = useRouteTransition(activeNodeId, route.nodeIds, reduceMotion)
  const layoutCache = useRef<{ signature: string; positions: Map<string, { x: number; y: number }> }>({ signature: '', positions: new Map() })
  const pendingFocusId = useRef<string | null>(null)
  useEffect(() => { setCollapsedIds((current) => new Set([...current].filter((id) => branches.some((branch) => branch.id === id)))) }, [branches])
  useEffect(() => { if (!activeNodeId) return; const hidden = findCollapsedBranchForNode(activeNodeId, branches, collapsedIds); if (hidden) setCollapsedIds((current) => { const next = new Set(current); next.delete(hidden.id); return next }) }, [activeNodeId, branches, collapsedIds])
  const collapsed = useMemo(() => resolveCollapsedGraph(domainNodes, connections, branches, collapsedIds), [branches, collapsedIds, connections, domainNodes]); const transitionOrder = useMemo(() => new Map([...route.nodeIds].reverse().map((id, index) => [id, index])), [route.nodeIds])
  const toggleBranch = useCallback((branchId: string) => setCollapsedIds((current) => { const next = new Set(current); if (next.has(branchId)) next.delete(branchId); else next.add(branchId); return next }), [])
  const graphEdges = useMemo<Edge[]>(() => { const visible = collapsed.visibleConnections.map((edge) => { const state = getGraphEdgeState(nodeById.get(edge.sourceNodeId), nodeById.get(edge.targetNodeId), routeEdges, edge.id); const step = Math.max(0, [...route.connectionIds].reverse().indexOf(edge.id)); return { id: edge.id, type: 'routeMap', source: edge.sourceNodeId, target: edge.targetNodeId, markerEnd: { type: MarkerType.ArrowClosed }, className: `graph-edge graph-edge-${state} ${transitioning && routeEdges.has(edge.id) ? 'graph-edge-transitioning' : ''}`, style: { '--route-step': step } as React.CSSProperties, animated: state === 'route' && !reduceMotion } }); const summaries = collapsed.collapsedBranches.map((branch) => ({ id: `summary-edge:${branch.id}`, type: 'routeMap', source: branch.sourceNodeId, target: `branch-summary:${branch.id}`, className: 'graph-edge graph-edge-summary', markerEnd: { type: MarkerType.ArrowClosed } })); return [...visible, ...summaries] }, [collapsed, nodeById, reduceMotion, route.connectionIds, routeEdges, transitioning])
  const graphNodes = useMemo<GraphFlowNode[]>(() => { const actual: TaskFlowNode[] = collapsed.visibleNodes.map((node) => ({ id: node.id, type: 'praxis', position: { x: 0, y: 0 }, data: { node, milestone: milestoneByNode.get(node.id), selected: node.id === selectedNodeId, active: node.id === activeNodeId, onRoute: routeNodes.has(node.id), presentation: visualById.get(node.id)!, transitionIndex: transitionOrder.get(node.id) ?? 0, transitioning: transitioning && routeNodes.has(node.id), collapsibleBranches: branches.filter((branch) => branch.sourceNodeId === node.id).map((branch) => ({ id: branch.id, count: branch.nodeIds.length, collapsed: collapsedIds.has(branch.id) })), onSelect: onSelectNode, onAdvance, onToggleBranch: toggleBranch } })); const summaries: BranchSummaryFlowNode[] = collapsed.collapsedBranches.map((branch) => ({ id: `branch-summary:${branch.id}`, type: 'branchSummary', position: { x: 0, y: 0 }, data: { branchId: branch.id, count: branch.nodeIds.length, onExpand: toggleBranch } })); const all = [...actual, ...summaries]; const signature = `${theme}|${all.map((node) => node.id).sort().join(',')}|${graphEdges.map((edge) => `${edge.source}>${edge.target}`).sort().join(',')}`; if (layoutCache.current.signature !== signature) { const laidOut = layoutGraph(all, graphEdges, theme === 'tech' ? techGraphNodeHeight : graphNodeHeight); layoutCache.current = { signature, positions: new Map(laidOut.map((node) => [node.id, node.position])) } } return all.map((node) => ({ ...node, position: layoutCache.current.positions.get(node.id) ?? node.position })) }, [activeNodeId, branches, collapsed, collapsedIds, graphEdges, milestoneByNode, onAdvance, onSelectNode, routeNodes, selectedNodeId, toggleBranch, transitionOrder, transitioning, visualById, theme])
  const [flowNodes, setFlowNodes, onNodesChange] = useNodesState<GraphFlowNode>(graphNodes); const [flowEdges, setFlowEdges, onEdgesChange] = useEdgesState(graphEdges); useLayoutEffect(() => setFlowNodes((current) => { const existing = new Map(current.map((node) => [node.id, node])); return graphNodes.map((node) => { const previous = existing.get(node.id); return previous ? ({ ...previous, ...node, data: node.data, position: node.position } as GraphFlowNode) : node }) }), [graphNodes, setFlowNodes]); useLayoutEffect(() => setFlowEdges(graphEdges), [graphEdges, setFlowEdges])
  const focusNode = useCallback((nodeId: string, duration: number) => { const flow = instance; const target = flow?.getNode(nodeId); if (!flow || !target?.measured?.width || !target.measured.height) { pendingFocusId.current = nodeId; return } pendingFocusId.current = null; requestAnimationFrame(() => { const ready = flow.getNode(nodeId); if (ready?.measured?.width && ready.measured.height) void flow.fitView({ nodes: [{ id: nodeId }], duration, padding: 1.25, maxZoom: 1.05 }) }) }, [instance])
  useEffect(() => { const targetId = pendingFocusId.current; if (targetId && flowNodes.some((node) => node.id === targetId)) focusNode(targetId, reduceMotion ? 0 : 500) }, [flowNodes, focusNode, reduceMotion])
  useEffect(() => { if (!activeNodeId || !transitioning) return; pendingFocusId.current = activeNodeId; const timer = window.setTimeout(() => focusNode(activeNodeId, reduceMotion ? 0 : 520), reduceMotion ? 0 : 420); return () => window.clearTimeout(timer) }, [activeNodeId, focusNode, reduceMotion, transitioning])
  const connect = useCallback(async (value: Connection) => { if (value.source && value.target && !value.source.startsWith('branch-summary:') && !value.target.startsWith('branch-summary:')) await onConnect(value.source, value.target) }, [onConnect]); const selected = domainNodes.find((node) => node.id === selectedNodeId); const protectedNode = selected ? routeNodes.has(selected.id) : false
  const locateActive = () => { if (activeNodeId) focusNode(activeNodeId, reduceMotion ? 0 : 500) }
  const focusRoute = () => {
    if (!instance || !route.nodeIds.length) return
    const visibleRoute = route.nodeIds.filter((id) => instance.getNode(id)?.measured?.width)
    if (visibleRoute.length) void instance.fitView({ nodes: visibleRoute.map((id) => ({ id })), duration: reduceMotion ? 0 : 520, padding: 0.38, maxZoom: theme === 'game' ? 1.14 : 1.05 })
  }
  const fitMap = () => { if (instance) void instance.fitView({ duration: reduceMotion ? 0 : 480, padding: domainNodes.length <= 3 ? 0.26 : (theme === 'tech' ? 0.1 : 0.16), maxZoom: theme === 'game' ? 1 : theme === 'tech' ? 1.05 : 0.9 }) }
  return <div className="task-graph-layout mt-6 grid gap-4 xl:grid-cols-[minmax(0,1fr)_300px]"><div className={`task-graph relative ${transitioning ? 'task-graph-transitioning' : ''}`} aria-label="项目路线图"><div className="graph-toolbar"><div className="tech-only graph-system-title" aria-hidden="true"><span>Route Topology</span><small>{domainNodes.length} NODES · {connections.length} LINKS · {branches.length} BRANCHES</small></div><div className="game-only graph-map-title" aria-hidden="true"><span>Quest Route Map</span><small>{route.nodeIds.length} 路线节点 · {branches.length} 条支线</small></div><div className="graph-toolbar-actions"><button className="button-secondary !px-3 !py-2 text-xs" disabled={!activeNodeId} onClick={locateActive}><Crosshair size={15} /><span>定位目标</span></button><button className="tech-only graph-system-action" disabled={!route.nodeIds.length} onClick={focusRoute}><LocateFixed size={15} /><span>聚焦路线</span></button><button className="tech-only graph-system-action" onClick={fitMap}><MapIcon size={15} /><span>适应全图</span></button><button className="game-only graph-map-action" disabled={!route.nodeIds.length} onClick={focusRoute}><LocateFixed size={15} /><span>聚焦路线</span></button><button className="game-only graph-map-action" onClick={fitMap}><MapIcon size={15} /><span>适应全图</span></button></div></div><div className="tech-only graph-coordinate-readout" aria-hidden="true"><span>PRAXIS LAB / TOPOLOGY VIEW</span><span>GRID 28 · LIVE</span></div><div className="game-only graph-map-compass" aria-hidden="true"><span>N</span><i /><small>Praxis Atlas</small></div><ReactFlow nodes={flowNodes} edges={flowEdges} nodeTypes={{ praxis: TaskGraphNode, branchSummary: BranchSummaryNode }} edgeTypes={{ routeMap: RouteMapEdge }} onInit={setInstance} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onConnect={(value) => void connect(value)} onNodeClick={(_, node) => { if (node.type === 'praxis') onSelectNode((node as TaskFlowNode).data.node) }} onEdgeDoubleClick={(_, edge) => { if (!edge.id.startsWith('summary-edge:') && window.confirm('断开这两个节点之间的连接？')) void onDisconnect(edge.id) }} fitView fitViewOptions={{ padding: domainNodes.length <= 3 ? 0.26 : (theme === 'tech' ? 0.1 : 0.16), maxZoom: domainNodes.length <= 3 ? (theme === 'game' ? 1.12 : theme === 'tech' ? 1.16 : 1.05) : (theme === 'game' ? 1 : theme === 'tech' ? 1.05 : 0.9), duration: reduceMotion ? 0 : 420 }} minZoom={0.38} maxZoom={1.55} deleteKeyCode={null}><Background color="rgb(var(--graph-grid-color))" gap={28} size={1} /><GraphMiniMap activeNodeId={activeNodeId} routeNodeIds={routeNodes} milestones={milestones} domainNodes={domainNodes} visualById={visualById} collapsedIds={collapsed.hiddenNodeIds} /><Controls showInteractive={false} /></ReactFlow><div className="sr-only" aria-live="polite">{collapsed.collapsedBranches.length ? `已收起 ${collapsed.collapsedBranches.length} 条支线，共隐藏 ${collapsed.hiddenNodeIds.size} 个节点` : '所有支线已展开'}</div></div>
    <aside className="graph-intel-panel surface-card h-fit p-5">{selected ? <><p className="eyebrow"><span className="theme-label-default">已选节点</span><span className="game-only">Quest Intel</span></p><h3 className="mt-2 font-serif text-xl text-text-primary"><span className="theme-label-default">任务节点</span><span className="game-only">据点情报</span></h3><p className="mt-3 text-sm leading-6 text-text-secondary">{selected.content}</p><div className="mt-5 grid gap-2">{selected.id === activeNodeId ? <><button className="button-primary justify-center" onClick={() => onAdvance(selected)}><Plus size={15} />继续推进</button><button className="button-secondary justify-center" onClick={() => onBranch(selected)}><GitBranch size={15} />创建支线</button><button className="button-secondary justify-center" onClick={onClearActive}><Unlink size={15} />取消追踪</button></> : <><button className="button-primary justify-center" onClick={() => onSetActive(selected)}><LocateFixed size={15} />设为当前目标</button><button className="button-secondary justify-center" onClick={() => onBranch(selected)}><GitBranch size={15} />创建支线</button></>}<button className="button-secondary justify-center" onClick={() => onMilestone(selected)}><Flag size={15} />{milestoneByNode.has(selected.id) ? '查看里程碑' : '设为里程碑'}</button><div className="grid grid-cols-2 gap-2"><button className="button-secondary justify-center" onClick={() => onEdit(selected)}><Edit3 size={15} />编辑</button><button className="button-secondary justify-center" disabled={protectedNode} title={protectedNode ? '当前路线节点不能删除' : '删除节点'} onClick={() => onDelete(selected)}><Trash2 size={15} />删除</button></div></div>{protectedNode && <p className="mt-3 text-[11px] text-text-secondary">当前路线受到保护；切换目标或取消追踪后才能删除。</p>}</> : <div className="py-8 text-center"><Target className="mx-auto text-accent-primary" /><p className="mt-3 text-sm text-text-secondary">选择节点以管理当前路线。</p></div>}<span className="sr-only">项目 {projectId}</span></aside></div>
}
