import dagre from '@dagrejs/dagre'
import { Background, Controls, Handle, MarkerType, MiniMap, Position, ReactFlow, useEdgesState, useNodesState, type Connection, type Edge, type Node, type NodeProps, type ReactFlowInstance } from '@xyflow/react'
import { CircleHelp, Crosshair, Edit3, Flag, GitBranch, Lightbulb, LocateFixed, Plus, Target, Trash2, Unlink } from 'lucide-react'
import { useCallback, useEffect, useMemo, useState } from 'react'
import type { CurrentRoute } from '../../domain/graph'
import type { Milestone, NodeConnection, PraxisNode } from '../../domain/types'
import { statusLabels, statusStyles } from '../../domain/rules'

const nodeWidth = 270; const nodeHeight = 160
interface GraphNodeData extends Record<string, unknown> { node: PraxisNode; milestone?: Milestone; selected: boolean; active: boolean; onRoute: boolean; needsChoice: boolean; onSelect: (node: PraxisNode) => void; onAdvance: (node: PraxisNode) => void }
type GraphNode = Node<GraphNodeData, 'praxis'>
const meta = { question: { label: '问题', icon: CircleHelp, tone: 'text-sky-400' }, solution: { label: '方案', icon: Lightbulb, tone: 'text-amber-400' }, result: { label: '结果', icon: Target, tone: 'text-emerald-400' } }

function PraxisGraphNode({ data }: NodeProps<GraphNode>) {
  const item = data.node; const Meta = meta[item.type]
  return <article className={`graph-node ${data.selected ? 'graph-node-selected' : ''} ${data.onRoute ? 'graph-node-route' : ''} ${data.active ? 'graph-node-active' : ''} ${data.needsChoice ? 'graph-node-choice' : ''}`} onClick={() => data.onSelect(item)}>
    <Handle type="target" position={Position.Left} className="graph-handle" /><div className="flex items-center justify-between gap-2"><span className={`inline-flex items-center gap-2 text-xs font-semibold ${Meta.tone}`}><Meta.icon size={15} />{Meta.label}</span><span className={`status-badge !px-2 !py-0.5 !text-[10px] ${statusStyles[item.status]}`}>{statusLabels[item.status]}</span></div>
    <div className="mt-2 flex min-h-5 items-center gap-2">{data.active && <span className="route-badge"><LocateFixed size={11} />当前目标</span>}{!data.active && data.onRoute && <span className="route-badge route-badge-subtle">当前路线</span>}{data.needsChoice && <span className="route-choice-badge">路线待确认</span>}</div>
    <p className="graph-node-content mt-2 text-sm leading-6 text-text-primary">{item.content}</p><div className="mt-3 flex items-center justify-between border-t border-line/15 pt-3"><span className="inline-flex items-center gap-1 text-[10px] text-text-secondary">{data.milestone ? <><Flag size={11} />里程碑</> : `#${item.position + 1}`}</span>{data.active && <button className="nodrag inline-flex items-center gap-1 text-xs font-medium text-accent-primary" onClick={(event) => { event.stopPropagation(); data.onAdvance(item) }}><Plus size={13} />继续推进</button>}</div><Handle type="source" position={Position.Right} className="graph-handle" />
  </article>
}
function layoutGraph(nodes: GraphNode[], edges: Edge[]) { const graph = new dagre.graphlib.Graph().setDefaultEdgeLabel(() => ({})); graph.setGraph({ rankdir: 'LR', ranksep: 100, nodesep: 55, marginx: 45, marginy: 45 }); nodes.forEach((node) => graph.setNode(node.id, { width: nodeWidth, height: nodeHeight })); edges.forEach((edge) => graph.setEdge(edge.source, edge.target)); dagre.layout(graph); return nodes.map((node) => { const p = graph.node(node.id); return { ...node, position: { x: p.x - nodeWidth / 2, y: p.y - nodeHeight / 2 } } }) }

interface Props { projectId: string; activeNodeId: string | null; route: CurrentRoute; nodes: PraxisNode[]; connections: NodeConnection[]; milestones: Milestone[]; selectedNodeId: string | null; onSelectNode: (node: PraxisNode) => void; onAdvance: (node: PraxisNode) => void; onBranch: (node: PraxisNode) => void; onSetActive: (node: PraxisNode) => void; onClearActive: () => void; onEdit: (node: PraxisNode) => void; onDelete: (node: PraxisNode) => void; onMilestone: (node: PraxisNode) => void; onConnect: (sourceId: string, targetId: string) => Promise<void>; onDisconnect: (connectionId: string) => Promise<void> }

export function TaskGraph({ projectId, activeNodeId, route, nodes: domainNodes, connections, milestones, selectedNodeId, onSelectNode, onAdvance, onBranch, onSetActive, onClearActive, onEdit, onDelete, onMilestone, onConnect, onDisconnect }: Props) {
  const routeNodes = useMemo(() => new Set(route.nodeIds), [route.nodeIds]); const routeEdges = useMemo(() => new Set(route.connectionIds), [route.connectionIds]); const [instance, setInstance] = useState<ReactFlowInstance<GraphNode, Edge> | null>(null)
  const graphEdges = useMemo<Edge[]>(() => connections.map((edge) => ({ id: edge.id, source: edge.sourceNodeId, target: edge.targetNodeId, markerEnd: { type: MarkerType.ArrowClosed }, className: routeEdges.has(edge.id) ? 'graph-edge graph-edge-route' : 'graph-edge graph-edge-muted', animated: routeEdges.has(edge.id) })), [connections, routeEdges])
  const graphNodes = useMemo<GraphNode[]>(() => layoutGraph(domainNodes.map((node) => ({ id: node.id, type: 'praxis', position: { x: 0, y: 0 }, data: { node, milestone: milestones.find((item) => item.nodeId === node.id), selected: node.id === selectedNodeId, active: node.id === activeNodeId, onRoute: routeNodes.has(node.id), needsChoice: node.id === route.needsChoiceNodeId, onSelect: onSelectNode, onAdvance } })), graphEdges), [activeNodeId, domainNodes, graphEdges, milestones, onAdvance, onSelectNode, route.needsChoiceNodeId, routeNodes, selectedNodeId])
  const [flowNodes, setFlowNodes, onNodesChange] = useNodesState<GraphNode>(graphNodes); const [flowEdges, setFlowEdges, onEdgesChange] = useEdgesState(graphEdges); useEffect(() => setFlowNodes(graphNodes), [graphNodes, setFlowNodes]); useEffect(() => setFlowEdges(graphEdges), [graphEdges, setFlowEdges])
  const connect = useCallback(async (value: Connection) => { if (value.source && value.target) await onConnect(value.source, value.target) }, [onConnect]); const selected = domainNodes.find((node) => node.id === selectedNodeId); const protectedNode = selected ? routeNodes.has(selected.id) : false
  const locateActive = () => { if (activeNodeId) void instance?.fitView({ nodes: [{ id: activeNodeId }], duration: 500, padding: 1.5, maxZoom: 1.15 }) }
  return <div className="mt-6 grid gap-4 xl:grid-cols-[minmax(0,1fr)_300px]"><div className="task-graph relative" aria-label="项目路线图"><button className="button-secondary absolute right-3 top-3 z-10 !px-3 !py-2 text-xs" disabled={!activeNodeId} onClick={locateActive}><Crosshair size={14} />定位当前目标</button><ReactFlow nodes={flowNodes} edges={flowEdges} nodeTypes={{ praxis: PraxisGraphNode }} onInit={setInstance} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onConnect={(value) => void connect(value)} onNodeClick={(_, node) => onSelectNode(node.data.node)} onEdgeDoubleClick={(_, edge) => { if (window.confirm('断开这两个节点之间的连接？')) void onDisconnect(edge.id) }} fitView minZoom={0.3} maxZoom={1.8} deleteKeyCode={null}><Background color="rgb(var(--border-soft))" gap={24} size={1} /><MiniMap pannable zoomable nodeColor={(node) => node.id === activeNodeId ? 'rgb(var(--accent-primary))' : 'rgb(var(--accent-secondary))'} maskColor="rgb(var(--bg-overlay) / 0.45)" /><Controls showInteractive={false} /></ReactFlow></div>
    <aside className="surface-card h-fit p-5">{selected ? <><p className="eyebrow">已选节点</p><h3 className="mt-2 font-serif text-xl text-text-primary">{meta[selected.type].label}节点</h3><p className="mt-3 text-sm leading-6 text-text-secondary">{selected.content}</p><div className="mt-5 grid gap-2">{selected.id === activeNodeId ? <><button className="button-primary justify-center" onClick={() => onAdvance(selected)}><Plus size={15} />继续推进</button><button className="button-secondary justify-center" onClick={() => onBranch(selected)}><GitBranch size={15} />创建支线</button><button className="button-secondary justify-center" onClick={onClearActive}><Unlink size={15} />取消追踪</button></> : <><button className="button-primary justify-center" onClick={() => onSetActive(selected)}><LocateFixed size={15} />设为当前目标</button><button className="button-secondary justify-center" onClick={() => onBranch(selected)}><GitBranch size={15} />创建支线</button></>}<button className="button-secondary justify-center" onClick={() => onMilestone(selected)}><Flag size={15} />{milestones.some((item) => item.nodeId === selected.id) ? '查看里程碑' : '设为里程碑'}</button><div className="grid grid-cols-2 gap-2"><button className="button-secondary justify-center" onClick={() => onEdit(selected)}><Edit3 size={15} />编辑</button><button className="button-secondary justify-center" disabled={protectedNode} title={protectedNode ? '当前路线节点不能删除' : '删除节点'} onClick={() => onDelete(selected)}><Trash2 size={15} />删除</button></div></div>{protectedNode && <p className="mt-3 text-[11px] text-text-secondary">当前路线受到保护；切换目标或取消追踪后才能删除。</p>}</> : <div className="py-8 text-center"><GitBranch className="mx-auto text-accent-primary" /><p className="mt-3 text-sm text-text-secondary">选择节点以管理当前路线。</p></div>}<span className="sr-only">项目 {projectId}</span></aside></div>
}
