import { Download, FileJson, ShieldCheck, Upload } from 'lucide-react'
import { useRef, useState } from 'react'
import { ConfirmDialog } from '../../components/Modal'
import { useToast } from '../../components/Toast'
import { repository } from '../../repositories/repository'

export function SettingsPage() {
  const input = useRef<HTMLInputElement>(null); const [pending, setPending] = useState<unknown>(null); const [mode, setMode] = useState<'merge' | 'replace'>('merge'); const { notify } = useToast()
  const download = async () => { const data = await repository.exportData(); const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `praxis-path-${new Date().toISOString().slice(0, 10)}.json`; anchor.click(); URL.revokeObjectURL(url); notify('备份文件已导出') }
  const selectFile = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; try { setPending(JSON.parse(await file.text())) } catch { notify('无法读取该 JSON 文件', 'error') } event.target.value = '' }
  const restore = async () => { try { await repository.importData(pending, mode); setPending(null); notify(mode === 'replace' ? '本地数据已从备份恢复' : '备份数据已合并') } catch { notify('备份结构无效，未修改现有数据', 'error'); setPending(null) } }
  return <div className="page-wrap"><header className="border-b border-ink/10 pb-8"><p className="eyebrow">本地数据</p><h1 className="page-title">数据设置</h1><p className="mt-3 max-w-2xl text-moss">所有内容保存在当前浏览器的 IndexedDB 中。请定期导出备份，尤其是在清理浏览器数据或更换域名前。</p></header><div className="mt-8 grid gap-6 lg:grid-cols-2"><section className="rounded-3xl border border-ink/10 bg-white/80 p-7"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-emerald-50 text-emerald-700"><Download /></span><h2 className="mt-5 font-serif text-2xl">导出完整备份</h2><p className="mt-2 text-sm leading-6 text-moss">项目、节点、里程碑验证和审视记录会保存为可阅读的 JSON 文件。</p><button className="button-primary mt-6" onClick={download}><FileJson size={17} />导出 JSON</button></section><section className="rounded-3xl border border-ink/10 bg-white/80 p-7"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-sky-50 text-sky-700"><Upload /></span><h2 className="mt-5 font-serif text-2xl">从备份恢复</h2><p className="mt-2 text-sm leading-6 text-moss">导入前会检查版本和实体字段。选择文件后可决定合并或覆盖。</p><div className="mt-5 flex gap-4 text-sm"><label className="flex items-center gap-2"><input type="radio" checked={mode === 'merge'} onChange={() => setMode('merge')} />合并数据</label><label className="flex items-center gap-2"><input type="radio" checked={mode === 'replace'} onChange={() => setMode('replace')} />覆盖本地数据</label></div><input ref={input} type="file" accept="application/json,.json" className="hidden" onChange={selectFile} /><button className="button-secondary mt-6" onClick={() => input.current?.click()}><Upload size={17} />选择备份文件</button></section></div><div className="mt-6 flex gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm leading-6 text-emerald-900"><ShieldCheck className="mt-0.5 shrink-0" size={19} /><p>本应用不会把你的项目上传到服务器。浏览器隐私模式、清理站点数据或更换访问域名都会使当前数据不可见，因此本地优先不等于无需备份。</p></div><ConfirmDialog open={pending !== null} title={mode === 'replace' ? '覆盖全部本地数据？' : '合并备份数据？'} message={mode === 'replace' ? '现有项目及所有关联记录将先被清空，再写入备份。此操作无法撤销。' : '同 ID 的记录将由备份版本替换，其他本地记录会保留。'} danger={mode === 'replace'} confirmLabel={mode === 'replace' ? '确认覆盖' : '确认合并'} onClose={() => setPending(null)} onConfirm={restore} /></div>
}
